#!/usr/bin/env python3
"""
Spritfill Sprite Validator

Validates Swift sprite code generated by an external LLM before you paste it into Xcode.

Usage:
    python3 validate_sprite.py sprite_file.swift

    Or paste directly:
    python3 validate_sprite.py      (then paste Swift code, press Ctrl+D when done)
"""

import sys
import re

# All valid palette hex colors (lowercase)
PALETTES = {
    "endesga64": {
        "#ff0040", "#131313", "#1b1b1b", "#272727", "#3d3d3d", "#5d5d5d", "#858585", "#b4b4b4",
        "#ffffff", "#c7cfdd", "#92a1b9", "#657392", "#424c6e", "#2a2f4e", "#1a1932", "#0e071b",
        "#1c121c", "#391f21", "#5d2c28", "#8a4836", "#bf6f4a", "#e69c69", "#f6ca9f", "#f9e6cf",
        "#edab50", "#e07438", "#c64524", "#8e251d", "#ff5000", "#ed7614", "#ffa214", "#ffc825",
        "#ffeb57", "#d3fc7e", "#99e65f", "#5ac54f", "#33984b", "#1e6f50", "#134c4c", "#0c2e44",
        "#00396d", "#0069aa", "#0098dc", "#00cdf9", "#0cf1ff", "#94fdff", "#fdd2ed", "#f389f5",
        "#db3ffd", "#7a09fa", "#3003d9", "#0c0293", "#03193f", "#3b1443", "#622461", "#93388f",
        "#ca52c9", "#c85086", "#f68187", "#f5555d", "#ea323c", "#c42430", "#891e2b", "#571c27",
    },
    "endesga32": {
        "#be4a2f", "#d77643", "#ead4aa", "#e4a672", "#b86f50", "#733e39", "#3e2731", "#a22633",
        "#e43b44", "#f77622", "#feae34", "#fee761", "#63c74d", "#3e8948", "#265c42", "#193c3e",
        "#124e89", "#0099db", "#2ce8f5", "#ffffff", "#c0cbdc", "#8b9bb4", "#5a6988", "#3a4466",
        "#262b44", "#181425", "#ff0044", "#68386c", "#b55088", "#f6757a", "#e8b796", "#c28569",
    },
    "zughy32": {
        "#472d3c", "#5e3643", "#7a444a", "#a05b53", "#bf7958", "#eea160", "#f4cca1", "#b6d53c",
        "#71aa34", "#397b44", "#3c5956", "#302c2e", "#5a5353", "#7d7071", "#a0938e", "#cfc6b8",
        "#dff6f5", "#8aebf1", "#28ccdf", "#3978a8", "#394778", "#39314b", "#564064", "#8e478c",
        "#cd6093", "#ffaeb6", "#f4b41b", "#f47e1b", "#e6482e", "#a93b3b", "#827094", "#4f546b",
    },
    "generic16": {
        "#000000", "#9d9d9d", "#ffffff", "#be2633", "#e06f8b", "#493c2b", "#a46422", "#eb8931",
        "#f7e26b", "#2f484e", "#44891a", "#a3ce27", "#1b2632", "#005784", "#31a2f2", "#b2dcef",
    },
    "pico8": {
        "#000000", "#1d2b53", "#7e2553", "#008751", "#ab5236", "#5f574f", "#c2c3c7", "#fff1e8",
        "#ff004d", "#ffa300", "#ffec27", "#00e436", "#29adff", "#83769c", "#ff77a8", "#ffccaa",
    },
}

CANVAS_SIZES = {
    ".smallSquare": (16, 16),
    ".mediumSquare": (32, 32),
    ".largeSquare": (64, 64),
    ".extraLargeSquare": (128, 128),
    ".wide": (64, 32),
    ".tall": (32, 64),
    ".landscape": (80, 60),
    ".portrait": (60, 80),
}


def split_sprites(code: str) -> list:
    """Split a file with multiple static let sprites into individual blocks."""
    pattern = r'(static let \w+:\s*PremadeSpriteData\s*=\s*\{.*?\}\s*\(\s*\))'
    blocks = re.findall(pattern, code, re.DOTALL)
    if blocks:
        return blocks
    # Fallback: try splitting by 'static let' boundaries
    parts = re.split(r'(?=\s*static let \w+:\s*PremadeSpriteData)', code)
    blocks = [p for p in parts if 'PremadeSpriteData' in p]
    if blocks:
        return blocks
    return [code]


def validate_one(code: str, sprite_name: str = ""):
    errors = []
    warnings = []

    # Extract canvas size
    canvas_match = re.search(r'canvasSize:\s*(\.\w+)', code)
    if not canvas_match:
        errors.append("Could not find canvasSize in the code")
        return errors, warnings

    canvas_key = canvas_match.group(1)
    if canvas_key not in CANVAS_SIZES:
        errors.append(f"Unknown canvasSize: {canvas_key}")
        errors.append(f"  Valid sizes: {', '.join(CANVAS_SIZES.keys())}")
        return errors, warnings

    width, height = CANVAS_SIZES[canvas_key]
    expected_total = width * height

    # Extract palette
    palette_match = re.search(r'palette:\s*\.(\w+)', code)
    palette_name = palette_match.group(1) if palette_match else None
    valid_colors = PALETTES.get(palette_name, set()) if palette_name else set()

    # Extract all grid elements
    grid_match = re.search(r'let grid:\s*\[String\]\s*=\s*\[(.*?)\]', code, re.DOTALL)
    if not grid_match:
        errors.append("Could not find 'let grid: [String] = [...]' in the code")
        return errors, warnings

    grid_content = grid_match.group(1)

    # Remove comments
    grid_clean = re.sub(r'//[^\n]*', '', grid_content)

    # Extract elements
    elements = [e.strip().strip('"').strip("'") for e in grid_clean.split(',') if e.strip() and e.strip() not in ('', ']')]
    elements = [e for e in elements if e]

    actual_total = len(elements)

    # Check total count
    if actual_total != expected_total:
        errors.append(f"GRID SIZE MISMATCH: Expected {expected_total} elements ({width}×{height}), got {actual_total}")
        diff = expected_total - actual_total
        if diff > 0:
            errors.append(f"  Missing {diff} elements")
        else:
            errors.append(f"  {-diff} extra elements")

    # Resolve variable names to their hex values
    var_defs = re.findall(r'let\s+(\w+)\s*=\s*"([^"]*)"', code)
    var_map = {name: value for name, value in var_defs}

    invalid_colors = set()
    non_palette_colors = set()

    for elem in elements:
        resolved = var_map.get(elem, elem)
        if resolved == "clear":
            continue
        if not re.match(r'^#[0-9a-fA-F]{6}$', resolved):
            invalid_colors.add(resolved)
            continue
        if valid_colors and resolved.lower() not in valid_colors:
            non_palette_colors.add(resolved)

    if invalid_colors:
        errors.append(f"INVALID COLOR FORMAT: {invalid_colors}")
        errors.append("  Colors must be '#' followed by exactly 6 hex digits, e.g. '#ea323c'")

    if non_palette_colors:
        warnings.append(f"Colors not in {palette_name} palette: {non_palette_colors}")

    # Check row comments and per-row element counts
    row_comments = re.findall(r'//\s*row\s*(\d+)', grid_content)
    if row_comments:
        row_nums = [int(r) for r in row_comments]
        expected_rows = list(range(height))
        missing_rows = set(expected_rows) - set(row_nums)
        if missing_rows:
            warnings.append(f"Missing row comments for rows: {sorted(missing_rows)}")

        row_sections = re.split(r'//\s*row\s*\d+', grid_content)[1:]
        for i, section in enumerate(row_sections):
            section_clean = re.sub(r'//[^\n]*', '', section)
            row_elements = [e.strip() for e in section_clean.split(',') if e.strip()]
            if len(row_elements) != width:
                errors.append(f"Row {i}: Expected {width} elements, got {len(row_elements)}")

    # Check required fields
    if not re.search(r'id:\s*"[^"]+"', code):
        errors.append("Missing 'id' field")
    if not re.search(r'name:\s*"[^"]+"', code):
        errors.append("Missing 'name' field")

    # Summary for valid sprites
    if not errors and not warnings:
        unique_colors = set()
        for elem in elements:
            resolved = var_map.get(elem, elem)
            if resolved != "clear":
                unique_colors.add(resolved.lower())
        clear_count = sum(1 for e in elements if var_map.get(e, e) == "clear")
        print(f"  ✅ {actual_total} pixels ({width}×{height}), {len(unique_colors)} colors, {clear_count} transparent")

    return errors, warnings


def main():
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
        with open(filepath, 'r') as f:
            code = f.read()
        print(f"Validating: {filepath}\n")
    else:
        print("Paste your Swift sprite code below, then press Ctrl+D:\n")
        code = sys.stdin.read()
        print()

    sprites = split_sprites(code)
    total_errors = 0
    total_warnings = 0

    for i, block in enumerate(sprites):
        name_match = re.search(r'static let (\w+)', block)
        name = name_match.group(1) if name_match else f"sprite_{i}"
        print(f"[{i+1}/{len(sprites)}] {name}")

        errors, warnings = validate_one(block, name)

        for w in warnings:
            print(f"  ⚠️  {w}")
        for e in errors:
            print(f"  ❌ {e}")

        total_errors += len(errors)
        total_warnings += len(warnings)

    print(f"\n{'─' * 40}")
    print(f"Sprites: {len(sprites)}  |  Errors: {total_errors}  |  Warnings: {total_warnings}")

    if total_errors > 0:
        print(f"\n💥 VALIDATION FAILED — fix errors before pasting into Xcode")
        sys.exit(1)
    else:
        print(f"\n🎉 All sprites valid! Ready to paste into Xcode.")
        print()
        print("Next steps:")
        print("  1. Save the Swift code to the appropriate file:")
        print("     - 16×16 non-character → PremadeSprites1616.swift")
        print("     - 16×16 character     → PremadeSpritesCharacters1616.swift")
        print("     - 32×32 non-character → PremadeSprites3232.swift")
        print("     - 32×32 character     → PremadeSpritesCharacters3232.swift")
        print("     - 64×64              → create PremadeSprites6464.swift")
        print("     - 128×128            → create PremadeSprites128128.swift")
        print("  2. Add sprite names to the 'all' array in PremadeSprites.swift")
        print("  3. Build and run!")


if __name__ == "__main__":
    main()
