//
//  DailyPromptService.swift
//  Spritfill
//
//  Created by Edmond Wu on 2026-03-20.
//

import Foundation

// Generates a deterministic daily drawing prompt from a curated list.
// All users see the same prompt on the same day — no network calls needed.
struct DailyPromptService {

    // Curated pixel-art-friendly drawing prompts (1000 total).
    private static let prompts: [String] = [
        "A tiny dragon sleeping on a pile of gold",
        "A cat sitting in a cardboard box",
        "A frog wearing a tiny crown",
        "An owl perched on a crescent moon",
        "A goldfish in a round fishbowl",
        "A bunny holding a carrot",
        "A penguin wearing a scarf",
        "A snail with a house on its back",
        "A bee hovering over a flower",
        "A fox curled up by a campfire",
        "A baby turtle hatching from an egg",
        "A sloth hanging from a tree branch",
        "A jellyfish glowing in the deep sea",
        "A tiny bird on a wire",
        "A hedgehog carrying an apple",
        "A corgi with a tiny backpack",
        "A chameleon blending into a rainbow",
        "A panda eating bamboo",
        "A flamingo standing on one leg",
        "A whale breaching the ocean surface",
        "A ladybug on a leaf",
        "A seahorse among coral",
        "A wolf howling at the moon",
        "A parrot on a pirate flag",
        "A butterfly with stained-glass wings",
        "A kitten tangled in yarn",
        "A hamster running on a wheel",
        "A deer in a misty forest",
        "An axolotl smiling underwater",
        "A toucan perched on a branch",
        "A raccoon rummaging through trash",
        "A red panda napping on a branch",
        "A firefly lighting up the night",
        "A hermit crab finding a new shell",
        "A duckling following its mother",
        "A koala hugging a eucalyptus tree",
        "A peacock displaying its feathers",
        "A scorpion in the moonlit desert",
        "A moth attracted to a lantern",
        "A baby chick pecking at seeds",
        "A bat hanging upside down in a cave",
        "An octopus juggling sea shells",
        "A swan on a calm lake",
        "A bear catching salmon in a river",
        "A fennec fox in the sand dunes",
        "A moose standing in shallow water",
        "A capybara relaxing in a hot spring",
        "A hummingbird at a feeder",
        "A clownfish hiding in an anemone",
        "A gecko climbing a wall",
        "A platypus swimming in a creek",
        "An eagle soaring above the clouds",
        "A chinchilla taking a dust bath",
        "A caterpillar on a mushroom",
        "A starfish on the ocean floor",
        "A baby elephant spraying water",
        "A narwhal under the northern lights",
        "A robin on a snowy fence post",
        "A chipmunk with full cheeks",
        "A blue jay on a mailbox",
        "A crab walking sideways on the beach",
        "A pufferfish inflated and surprised",
        "A manta ray gliding through the sea",
        "A llama wearing sunglasses",
        "A leopard resting in a tree",
        "A piglet rolling in the mud",
        "A koi fish in a garden pond",
        "An arctic fox in the snow",
        "A cricket on a blade of grass",
        "A sea otter holding hands with another",
        "A tortoise winning a race",
        "A flying squirrel mid-glide",
        "A tapir in a jungle clearing",
        "A baby seal on an ice floe",
        "A dragonfly over a lily pad",
        "A lemur with wide eyes",
        "A porcupine with colorful quills",
        "A pelican catching a fish",
        "A praying mantis in a garden",
        "A mountain goat on a cliff edge",
        "A salamander near a campfire",
        "A stingray buried in the sand",
        "An albatross flying over the ocean",
        "A tiny mouse stealing cheese",
        "A hippo yawning in a river",
        "A kangaroo with a joey in its pouch",
        "A barn owl in a hollow tree",
        "A caterpillar becoming a butterfly",
        "A yak on a snowy mountain path",
        "A bison on the plains at sunset",
        "A tree frog on a tropical leaf",
        "A sea turtle swimming with fish",
        "A dodo bird brought back to life",
        "A mythical griffin guarding treasure",
        "A phoenix rising from ashes",
        "A unicorn in an enchanted forest",
        "A baby kraken in a tide pool",
        "A cerberus guarding a gate",
        "A basilisk in a dungeon",
        "A chimera on a mountain",
        "A sprite riding a dragonfly",
        "A miniature fairy dragon",
        "A frost wolf in a blizzard",
        "An ember fox with a flaming tail",
        "A crystal spider in a cave",
        "A moss golem in the forest",
        "A thunder hawk in a storm",
        "A shadow cat with glowing eyes",
        "A water serpent coiled around a rock",
        "A cloud sheep floating in the sky",
        "A lava snail on volcanic rock",
        "A clockwork beetle",
        "A jade turtle with gems on its shell",
        "A storm whale in the sky",
        "A sandworm emerging from dunes",
        "A pixie riding a ladybug",
        "A mushroom creature with a lantern",
        "A ghostly wolf in the fog",
        "A mechanical owl with brass gears",
        "A tiny wyvern perched on a sword",
        "A star jellyfish in outer space",
        "A coral dragon in a reef",
        "A tundra fox with aurora fur",
        "A vine snake wrapped around a branch",
        "A magma salamander",
        "A wind hawk diving through clouds",
        "A twilight moth with glowing wings",
        "A stone gargoyle coming to life",
        "A bone dragon in a graveyard",
        "A candy slime monster",
        "A forest spirit shaped like a deer",
        "A rubber duck army",
        "A dog astronaut in space",
        "A cat wizard casting a spell",
        "A penguin riding a surfboard",
        "A pug with a superhero cape",
        "A llama at a tea party",
        "A dinosaur in a city",
        "A pigeon with a briefcase",
        "A squirrel hoarding acorns",
        "A catfish that looks like a cat",
        "Three wise monkeys",
        "A spider knitting a web sweater",
        "An ant carrying a crumb ten times its size",
        "A school of fish forming a bigger fish shape",
        "A rooster crowing at sunrise",
        "A chameleon on a disco ball",
        "A goldfinch on a thistle flower",
        "A horseshoe crab at the shore",
        "A pangolin curled into a ball",
        "A quokka smiling at the camera",
        "An ocelot hiding in the jungle",
        "A slice of pizza with melted cheese",
        "A steaming cup of coffee",
        "A stack of pancakes with syrup",
        "A cherry on top of a cupcake",
        "An ice cream cone with three scoops",
        "A bowl of ramen with chopsticks",
        "A juicy watermelon slice",
        "A donut with sprinkles",
        "A bento box with tiny compartments",
        "A bubble tea with tapioca pearls",
        "A sushi platter with wasabi",
        "A jar of cookies with the lid off",
        "A slice of layer cake",
        "A pretzel with mustard",
        "A taco with all the toppings",
        "A waffle with strawberries and cream",
        "A popsicle melting in the sun",
        "A basket of fresh bread",
        "A smoothie bowl with fruit toppings",
        "A candy bar with a bite taken out",
        "A steaming bowl of pho",
        "A plate of spaghetti and meatballs",
        "A croissant with butter",
        "A milkshake with a cherry on top",
        "A bag of popcorn at the movies",
        "A cheeseburger with all the fixings",
        "A fruit salad in a carved watermelon",
        "A fondue pot with dippers",
        "A box of assorted macarons",
        "A soft pretzel cart on a street corner",
        "A gingerbread house",
        "A hot dog with mustard and ketchup",
        "A cheese board with crackers",
        "A pot of soup with steam rising",
        "A basket of french fries",
        "A gyoza dumpling plate",
        "A jar of jam with a spoon in it",
        "A birthday cake with candles",
        "A glass of lemonade with ice",
        "A plate of nigiri sushi",
        "A cinnamon roll with icing",
        "An avocado toast on a plate",
        "A bowl of cereal with milk splashing",
        "A mug of hot chocolate with marshmallows",
        "A slice of pie with a lattice crust",
        "A dim sum steamer basket",
        "A caramel apple on a stick",
        "A bowl of bibimbap",
        "A cheese pizza fresh from the oven",
        "A plate of fish and chips",
        "A jar of honey with a dipper",
        "A meat skewer over a grill",
        "A peanut butter and jelly sandwich",
        "A plate of fresh spring rolls",
        "A cup of matcha latte",
        "A burrito wrapped in foil",
        "A bowl of acai with toppings",
        "A plate of takoyaki",
        "A candy cane",
        "A plate of waffles shaped like a heart",
        "An espresso machine pulling a shot",
        "A cocktail with a tiny umbrella",
        "A candy store window display",
        "A gumball machine full of colors",
        "A cotton candy on a stick",
        "A chocolate fountain with fruit",
        "A Thai iced tea with cream",
        "A French onion soup with melted cheese",
        "A lobster on a fancy plate",
        "A bowl of udon noodles",
        "A fruit tart with glazed berries",
        "A plate of curry with rice",
        "A Nutella crepe with bananas",
        "A corn on the cob with butter",
        "A basket of fried chicken",
        "A bowl of tomato soup with grilled cheese",
        "A plate of bruschetta",
        "A snow cone with rainbow syrup",
        "An egg sunny-side up in a pan",
        "A bagel with cream cheese and lox",
        "A plate of pad thai",
        "A root beer float",
        "A bowl of oatmeal with berries",
        "A cheese fondue with bread cubes",
        "A plate of nachos loaded with toppings",
        "A jar of pickles",
        "A fresh baguette in a paper bag",
        "A tiramisu in a glass cup",
        "A bubble waffle with ice cream",
        "A plate of mochi",
        "A cup of chai with spices",
        "A bowl of poke with tuna",
        "A plate of empanadas",
        "A bowl of clam chowder in a bread bowl",
        "A tray of freshly baked cookies",
        "A slice of New York cheesecake",
        "A Vietnamese banh mi sandwich",
        "A plate of pierogi with sour cream",
        "A bowl of congee with toppings",
        "A Turkish delight assortment",
        "A box of fresh donuts",
        "A platter of caprese salad",
        "A stack of onion rings",
        "A bowl of miso soup",
        "A plate of churros with chocolate sauce",
        "A tropical fruit platter",
        "A Korean corn dog with cheese",
        "A monte cristo sandwich",
        "A bowl of minestrone soup",
        "A plate of fresh oysters on ice",
        "A Japanese parfait dessert",
        "A plate of dango on a stick",
        "A cheese wheel being cut open",
        "A pint of craft beer with foam",
        "A coconut split open on the beach",
        "A plate of shakshuka",
        "A bowl of risotto with mushrooms",
        "A glass of sangria with fruit",
        "A plate of baklava",
        "A fresh juice being poured from a blender",
        "A campfire with marshmallows roasting",
        "A cup of Earl Grey with a lemon slice",
        "A basket of garlic knots",
        "A plate of peking duck",
        "A tower of macarons in pastel colors",
        "A tiny island with a single palm tree",
        "A mushroom house in a forest",
        "A cactus in a desert at sunset",
        "A lighthouse on a rocky cliff",
        "A cherry blossom tree in spring",
        "A mountain with a flag on top",
        "A rainbow after a storm",
        "A tiny waterfall into a pond",
        "A field of sunflowers",
        "A cozy cabin in the snow",
        "A volcano erupting at night",
        "An aurora borealis over a frozen lake",
        "A zen garden with raked sand",
        "A coral reef teeming with life",
        "A bamboo forest path",
        "A thunderstorm over the ocean",
        "A tide pool with tiny creatures",
        "A cave with crystals growing inside",
        "An oasis in the middle of a desert",
        "A meadow full of wildflowers",
        "A forest floor covered in fallen leaves",
        "A glacier with icebergs floating nearby",
        "A terraced rice paddy",
        "A canyon with a river at the bottom",
        "A redwood forest with giant trees",
        "A starry night over a wheat field",
        "A foggy morning on a lake",
        "A bioluminescent beach at night",
        "A hot spring in a snowy landscape",
        "A mangrove swamp at dusk",
        "A desert mesa at golden hour",
        "A lavender field in Provence",
        "A cliff face with a hidden cave",
        "A rainforest canopy from above",
        "A frozen waterfall in winter",
        "A savanna with an acacia tree at sunset",
        "A geothermal vent on the ocean floor",
        "A rolling hill of green grass",
        "A river delta from above",
        "A giant redwood with a door in it",
        "A crystal-clear mountain stream",
        "A moss-covered stone bridge",
        "A field of tulips in Holland",
        "A salt flat reflecting the sky",
        "A kelp forest underwater",
        "A windswept cliff by the sea",
        "An underground river in a cavern",
        "A petrified forest landscape",
        "A sand dune shaped like a wave",
        "A tidal island connected by a sandbar",
        "A rainforest waterfall with mist",
        "A snowy mountain pass",
        "A peaceful lake at dawn with mist",
        "A grove of aspen trees in fall",
        "An icy tundra with Northern Lights",
        "A sinkhole revealing an underground world",
        "A fjord with steep cliffs",
        "A swamp with cypress trees and moss",
        "A meteor crater filled with water",
        "A prairie at sunset with tall grass",
        "A volcanic island with black sand beaches",
        "An emerald mine inside a mountain",
        "A spring thaw with melting snow and wildflowers",
        "A weathered desert arch",
        "A peat bog with strange light",
        "A cloud forest with orchids",
        "A tundra with a lone polar bear",
        "A rocky coastline with crashing waves",
        "A moonlit river through a forest",
        "A garden after rain with droplets on petals",
        "A coral atoll from above",
        "A misty mountain peak at sunrise",
        "A river of lava at night",
        "A hidden waterfall behind vines",
        "A field of poppies in the wind",
        "A secluded beach with turquoise water",
        "A towering cliff with nesting birds",
        "A canyon painted with sunset colors",
        "A forest clearing with a beam of light",
        "A frost-covered spider web at dawn",
        "An autumn forest reflected in a lake",
        "A tiny creek with stepping stones",
        "A plateau above the clouds",
        "A vine-covered ancient wall in a jungle",
        "A desert night sky with the Milky Way",
        "A seaside cave with a treasure inside",
        "A marsh at sunset with fireflies",
        "A tropical storm approaching an island",
        "A peaceful brook through mossy rocks",
        "A limestone karst landscape",
        "A wildfire-scorched forest regrowing",
        "A snow-capped mountain reflected in a lake",
        "A dry riverbed with cracked earth",
        "A sunken shipwreck covered in coral",
        "A bluff overlooking a vast valley",
        "A raindrop on a leaf zoomed in",
        "An underwater cave with light streaming in",
        "A hilltop covered in heather",
        "A forest path in deep winter snow",
        "A tide coming in over a sandy beach",
        "A double rainbow over a valley",
        "A grove of bioluminescent mushrooms",
        "A hot desert mirage on the horizon",
        "A tornado touching down on farmland",
        "A sunbeam through dark clouds over the sea",
        "A wildflower-covered mountainside",
        "An ancient petrified tree stump",
        "A river bend with autumn foliage",
        "A tropical reef seen from the surface",
        "A quiet pond with lily pads and frogs",
        "A terraced hillside with small farms",
        "A blizzard whiting out a forest",
        "A palm tree silhouette at sunset",
        "A ravine with a rope bridge",
        "A mountain trail with alpine flowers",
        "A winter forest with fresh animal tracks",
        "A tiny waterfall in a mossy grotto",
        "A sky full of hot air balloons over fields",
        "An island with a single tree and a hammock",
        "A coastline shaped like a dragon",
        "A deep dark cave with a distant glow",
        "A field of snow with a red barn",
        "A volcanic hot spring with colored minerals",
        "A majestic fjord under midnight sun",
        "A moss garden in a temple courtyard",
        "A rainbow eucalyptus forest",
        "A path through a tunnel of cherry blossoms",
        "A cliffside village at sunrise",
        "A desert canyon with ancient cave art",
        "A river mouth meeting the ocean",
        "A frozen lake with ice skaters",
        "A miniature world inside a terrarium",
        "A botanical garden greenhouse",
        "A sunset over a cypress swamp",
        "A crystal geode cracked open",
        "An alpine lake fed by glaciers",
        "A tree growing on a tiny island in a lake",
        "A cliff diving spot with emerald water below",
        "A rain-soaked cobblestone path through woods",
        "A desert bloom after a rare rain",
        "A kelp-covered sea cave",
        "A mountain goat trail on a narrow ledge",
        "A willow tree over a quiet pond",
        "A treasure chest overflowing with gems",
        "A magic potion bottle",
        "A pixel-art sword with a glowing blade",
        "A retro game controller",
        "A crystal ball on a stand",
        "A lantern glowing in the dark",
        "A pair of headphones",
        "A vintage camera",
        "A rocket ship blasting off",
        "A hot air balloon over mountains",
        "A compass pointing north",
        "A snow globe with a tiny world inside",
        "A gramophone playing music notes",
        "A stack of old books with a candle",
        "A telescope pointed at the stars",
        "An hourglass with sand trickling down",
        "A magnifying glass over a map",
        "A typewriter with a letter in it",
        "A music box with a ballerina",
        "A ship in a bottle",
        "A pocket watch showing midnight",
        "A skeleton key on a velvet cushion",
        "A set of RPG dice",
        "A magic wand with sparkles",
        "A quill pen and inkwell",
        "A globe on a wooden desk",
        "A lava lamp glowing in the dark",
        "A toolbox with tools spilling out",
        "A piggy bank with a coin going in",
        "A mason jar full of fireflies",
        "A vintage rotary phone",
        "A cassette tape with the label showing",
        "A pair of ruby slippers",
        "A crown sitting on a pillow",
        "A jack-in-the-box popping open",
        "A dreamcatcher with feathers",
        "A nesting doll set",
        "A wrapped gift box with a bow",
        "An antique mirror on a wall",
        "A cuckoo clock striking the hour",
        "A message in a bottle",
        "A lighthouse lantern close-up",
        "A spinning top in motion",
        "A pinball machine lit up",
        "A jukebox playing a favorite song",
        "An arcade cabinet with a high score",
        "A chemistry set with bubbling flasks",
        "A leather-bound journal",
        "A wizard staff with a crystal",
        "A shield with a dragon emblem",
        "A treasure map with an X",
        "A magic mirror with a glowing frame",
        "A pair of binoculars looking out",
        "A kaleidoscope pattern",
        "A mechanical clock with exposed gears",
        "A Japanese folding fan",
        "A ceramic vase with painted flowers",
        "A candelabra with dripping wax",
        "A miniature train set on a table",
        "A sewing machine with colorful thread",
        "A skateboard with a custom design",
        "A surfboard stuck in the sand",
        "A pair of ice skates",
        "A guitar leaning against an amp",
        "A drum kit on a stage",
        "A piano keyboard close-up",
        "A violin with a bow",
        "A turntable spinning a vinyl record",
        "A microphone on a stage with spotlights",
        "A backpack ready for adventure",
        "A pair of hiking boots",
        "A camping tent under the stars",
        "A Swiss army knife with tools open",
        "A pair of sunglasses reflecting a sunset",
        "A vintage suitcase with stickers",
        "A bicycle with a basket of flowers",
        "A sailboat on calm water",
        "An anchor on the seabed",
        "A life preserver floating on water",
        "A diving helmet from the old days",
        "A pair of boxing gloves",
        "A basketball going through a hoop",
        "A soccer ball on a field",
        "A baseball and glove",
        "A fishing rod with a catch",
        "A bow and arrow hitting a bullseye",
        "A chess set mid-game",
        "A paper crane made from origami",
        "A bonsai tree in a ceramic pot",
        "A terrarium with tiny succulents",
        "A paintbrush and palette",
        "A pair of scissors and cut paper",
        "A spool of golden thread",
        "A vintage alarm clock ringing",
        "A rocking chair on a porch",
        "A mailbox with letters sticking out",
        "A birdhouse hanging from a tree",
        "A wind chime in a breeze",
        "A garden gnome among flowers",
        "A street lamp glowing at dusk",
        "A park bench under a tree",
        "A fountain in a town square",
        "A wishing well with a bucket",
        "A wooden barrel full of apples",
        "A watering can with flowers",
        "A pot of gold at the end of a rainbow",
        "A magic carpet hovering",
        "A genie lamp with smoke",
        "A crystal pendant glowing softly",
        "An enchanted book with pages fluttering",
        "A pair of wings made of light",
        "A floating orb of energy",
        "A glowing rune circle on the ground",
        "A portal frame made of obsidian",
        "A healing potion in a heart-shaped bottle",
        "A mana crystal in a cave",
        "A scroll with ancient writing",
        "A welcome mat at a front door",
        "A fire hydrant on a city corner",
        "A traffic light changing colors",
        "A wheelbarrow in a garden",
        "A snow shovel next to a snowman",
        "A conductor baton mid-swing",
        "A knight standing guard",
        "A wizard casting a spell",
        "A robot waving hello",
        "A pirate with a parrot on their shoulder",
        "An astronaut floating in space",
        "A tiny chef cooking in a kitchen",
        "A ninja hiding behind a wall",
        "A ghost peeking around a corner",
        "A mermaid sitting on a rock",
        "A vampire under a full moon",
        "A samurai drawing their sword",
        "A cowboy in a standoff",
        "A detective with a magnifying glass",
        "An alchemist in a cluttered lab",
        "A dancer mid-pirouette",
        "A bard playing a lute by a fire",
        "A blacksmith at the forge",
        "A queen on a balcony overlooking her kingdom",
        "A thief sneaking through shadows",
        "A monk meditating on a mountain",
        "A gladiator in an arena",
        "A fairy sprinkling pixie dust",
        "A dwarf mining in a cave",
        "An elf archer in a forest",
        "A druid communing with nature",
        "A cleric healing a wounded ally",
        "A necromancer raising the undead",
        "A ranger tracking footprints",
        "A merchant at a market stall",
        "A sailor on a ship deck in a storm",
        "A mad scientist in a lightning-lit lab",
        "A superhero on a rooftop at night",
        "A time traveler stepping out of a portal",
        "A Viking on a longship",
        "A Roman centurion with a shield",
        "A pharaoh on a golden throne",
        "An oracle gazing into a pool of water",
        "A witch brewing a potion in a cauldron",
        "A paladin raising a glowing sword",
        "A jester performing for a king",
        "A librarian in a vast magical library",
        "A gardener tending to magical plants",
        "A fisherman on a dock at sunrise",
        "A clockmaker working on a tiny mechanism",
        "A glassblower shaping a vase",
        "A potter at a spinning wheel",
        "A baker pulling bread from an oven",
        "A candlemaker dipping wicks",
        "A cartographer drawing a fantasy map",
        "A beekeeper checking a hive",
        "A lumberjack in a snowy forest",
        "A chimney sweep on a rooftop",
        "A lighthouse keeper at twilight",
        "A fortune teller with tarot cards",
        "A street musician playing saxophone",
        "A painter at an easel in a park",
        "A photographer snapping a sunset",
        "A florist arranging a bouquet",
        "A mailcarrier on their rounds",
        "A farmer on a tractor at harvest",
        "A firefighter rescuing a cat from a tree",
        "A lifeguard watching the beach",
        "A diver exploring a shipwreck",
        "A mountain climber at the summit",
        "A skateboarder doing a kickflip",
        "A surfer riding a big wave",
        "A snowboarder catching air",
        "A skier on a powder day",
        "A rock climber on a cliff face",
        "A pilot in a cockpit above the clouds",
        "A train conductor waving from the engine",
        "A barista making latte art",
        "A sushi chef slicing fish",
        "A pizza maker tossing dough",
        "A DJ at a turntable with colorful lights",
        "An orchestra conductor mid-performance",
        "A ballet dancer on a moonlit stage",
        "A figure skater in a sparkling outfit",
        "A martial artist breaking a board",
        "A gymnast mid-flip on a beam",
        "A boxer in the ring under spotlights",
        "A fencer in a lunge position",
        "A cyclist racing on a velodrome",
        "A rower on a misty morning river",
        "A chess master deep in thought",
        "Two friends sharing a milkshake",
        "A child blowing out birthday candles",
        "A grandparent reading to a grandchild",
        "A couple watching a sunset from a pier",
        "A family having a picnic in a meadow",
        "A group of friends around a campfire",
        "Kids playing in a sprinkler",
        "A person walking a dog in the park",
        "Someone reading a book under a big tree",
        "A busker performing on a cobbled street",
        "A child letting go of a red balloon",
        "Two cats sitting on a windowsill together",
        "A person meditating at sunrise",
        "Someone flying a kite on a windy hill",
        "A kid splashing in rain puddles",
        "A person gazing through a telescope at night",
        "A traveler at a train station with a map",
        "A student falling asleep at their desk",
        "A person opening a mysterious door",
        "Someone discovering a hidden room",
        "A brave hero entering a dark cave",
        "A character running from a rolling boulder",
        "Two rivals having a cooking battle",
        "A person finding a message in a bottle",
        "A character planting a flag on a new planet",
        "Someone befriending a wild animal",
        "A hero standing on a cliff overlooking the land",
        "A character choosing between two paths",
        "A villain sitting on a dark throne",
        "A healer tending to a wounded creature",
        "A scholar deciphering an ancient tablet",
        "An inventor testing a flying machine",
        "A character looking into a magic mirror",
        "Two old friends meeting after a long journey",
        "A group of adventurers at a tavern table",
        "A child building a sandcastle on the beach",
        "A person writing a letter by candlelight",
        "A character waking up in a strange world",
        "Someone finding a lost pet",
        "A hero returning home after an adventure",
        "A character riding a giant bird",
        "Two people dancing in the rain",
        "A person catching a shooting star in a jar",
        "A child discovering a secret garden",
        "A character making friends with a ghost",
        "Someone painting a self-portrait",
        "A person at the top of a ferris wheel at night",
        "A character opening a time capsule",
        "Two pen pals meeting for the first time",
        "A musician playing for the animals of the forest",
        "Someone releasing paper lanterns into the sky",
        "A character riding a bicycle through a village",
        "A person feeding birds in a snowy park",
        "A taxi driver in a rainy city at night",
        "A delivery person with a stack of packages",
        "An ice cream truck driver on a summer day",
        "A bus driver at a stop",
        "A medieval castle on a hilltop",
        "A Japanese pagoda in autumn",
        "A treehouse connected by rope bridges",
        "A cozy cottage with smoke from the chimney",
        "A windmill in a tulip field",
        "An underwater domed city",
        "A space station orbiting Earth",
        "A Roman colosseum at sunset",
        "A spooky haunted mansion",
        "A fairy-tale tower with a long window",
        "A desert pyramid under the stars",
        "A floating sky fortress",
        "A hobbit hole in a hillside",
        "A neon-lit cyberpunk alley",
        "A Victorian greenhouse full of plants",
        "A stone bridge over a misty river",
        "A log cabin by a mountain lake",
        "A Chinese moon gate in a garden",
        "A ruined temple overgrown with vines",
        "A market square in a fantasy town",
        "A clock tower in a town center",
        "A library with floor-to-ceiling bookshelves",
        "A blacksmith forge with glowing coals",
        "A bakery with pastries in the window",
        "A flower shop with a colorful awning",
        "A cozy bookshop on a rainy street",
        "A general store in a Wild West town",
        "A potion shop with shelves of bottles",
        "A toy store window at Christmas",
        "A diner with a neon sign at night",
        "A jazz club with smoky atmosphere",
        "A rooftop garden in a city",
        "A subway station with tile art",
        "A covered bridge in fall foliage",
        "An igloo under the Northern Lights",
        "A sandcastle that looks like a real castle",
        "A mushroom village for tiny creatures",
        "A candy house in a forest",
        "A glass palace reflecting the sunset",
        "A tree with a spiral staircase around it",
        "A church with stained glass windows",
        "A shrine gate with autumn leaves",
        "A Greek temple overlooking the sea",
        "A houseboat on a calm canal",
        "A train station platform at dusk",
        "A dock with fishing boats",
        "A marina full of sailboats",
        "A beach hut with surfboards outside",
        "A ski lodge with snow on the roof",
        "A drive-in movie theater at night",
        "A carnival with a lit-up ferris wheel",
        "A greenhouse filled with exotic plants",
        "A barn with animals peeking out",
        "A farmhouse with a wrap-around porch",
        "A city skyline at golden hour",
        "A bridge lit up at night over a river",
        "A street lined with cherry blossom trees",
        "A cobblestone alley with hanging lanterns",
        "A balcony garden in a European city",
        "A rooftop pool overlooking the skyline",
        "A secret room behind a bookshelf",
        "A dungeon corridor with flickering torches",
        "A throne room with a red carpet",
        "A wizard study with floating books",
        "An enchanted greenhouse with glowing plants",
        "A dragon hoard in a vast cavern",
        "A hidden rebel base in a cave",
        "A control room with many screens",
        "A cozy reading nook by a window",
        "A hammock between two trees by the beach",
        "A tent pitched on a mountain ledge",
        "A space habitat module on Mars",
        "A coral castle built by mermaids",
        "A cloud city in the sky",
        "An underground dwarven hall",
        "A steampunk airship docking tower",
        "A crystal palace in a snowy land",
        "A tree fort in a giant banyan tree",
        "A waterfall hiding a secret grotto home",
        "A fire lookout tower at sunset",
        "A covered market with hanging lights",
        "A tiny house on wheels on a country road",
        "A boat converted into a floating cafe",
        "A library carved into a cliff face",
        "An observatory dome under the stars",
        "A bird nest the size of a house",
        "An airport terminal at sunset",
        "A mosque with ornate tilework",
        "A monster lair with scattered bones",
        "Your mood today as a color palette",
        "A portal to another dimension",
        "A heart made of smaller hearts",
        "The four seasons in one scene",
        "A yin-yang symbol with a twist",
        "An impossible staircase",
        "A pixel-art QR code that looks cool",
        "A tiny planet with its own ecosystem",
        "A clock melting like in a Dali painting",
        "Symmetrical geometric pattern",
        "A gradient that tells a story",
        "An optical illusion in pixel art",
        "A fractal pattern made of squares",
        "A mosaic of your favorite things",
        "The concept of time in one image",
        "Music visualized as colored shapes",
        "A word drawn as the thing it describes",
        "An emotion represented by weather",
        "Day turning into night in a single scene",
        "A scene that looks different upside down",
        "A pattern that tiles seamlessly",
        "Your favorite number as a character",
        "The inside of a computer chip",
        "Data flowing through a network",
        "A loading bar that tells a mini story",
        "A pixel-art emoji that does not exist yet",
        "A color wheel made of objects",
        "An alphabet made of animals",
        "A mandala pattern with pixel precision",
        "A stained glass window design",
        "A Celtic knot pattern",
        "An Islamic geometric pattern",
        "A Japanese wave pattern",
        "A nordic rune circle",
        "A circuit board that looks like a city",
        "A DNA helix in neon colors",
        "A constellation map of a zodiac sign",
        "The solar system in a single frame",
        "A black hole with an accretion disk",
        "A nebula with swirling colors",
        "A supernova explosion in slow motion",
        "A mathematical spiral in nature",
        "The golden ratio visualized",
        "A world map in pixel art",
        "A cross-section of a planet",
        "The water cycle in one scene",
        "A food chain illustrated",
        "An atom with orbiting electrons",
        "A crystal structure zoomed in",
        "A snowflake with unique geometry",
        "A fingerprint pattern in detail",
        "A maze with a hidden message",
        "A pixel-art barcode",
        "Binary code spelling your name",
        "A pixel-art depth illusion",
        "A scene that combines fire and ice",
        "A scene that combines land and sea",
        "Light and shadow playing on a wall",
        "Reflections in a puddle after rain",
        "A prism splitting white light into colors",
        "A candle flame in extreme detail",
        "The life cycle of a star",
        "A seed growing into a massive tree",
        "A butterfly wing pattern close-up",
        "A geode with layers of color",
        "A lava lamp in abstract style",
        "Sound waves from a speaker",
        "A heartbeat monitor pattern",
        "A topographic map of a fantasy land",
        "Your bedroom reimagined in pixel art",
        "A dream you had recently",
        "Your favorite song as a scene",
        "Your pet if it were a fantasy creature",
        "Your initials as a decorative emblem",
        "A self portrait using only 4 colors",
        "A still life with unusual objects",
        "The view from your window",
        "A place you want to visit someday",
        "Your favorite memory as a pixel scene",
        "The cover of your favorite book",
        "A scene from your favorite movie",
        "A flag for an imaginary country",
        "A coat of arms for your family",
        "A logo for a fictional company",
        "A crossword puzzle design",
        "A raindrop journey from cloud to ground",
        "A Native American-inspired pattern",
        "Evolution from fish to human in frames",
        "A timeline of human history compressed",
        "A pixel-art representation of pi",
        "A jack-o-lantern with a spooky face",
        "A snowman with a top hat",
        "A wrapped present with a bow",
        "A firework exploding in the night sky",
        "An Easter egg with a fancy pattern",
        "A four-leaf clover",
        "A beach scene with an umbrella",
        "A cozy fireplace with stockings",
        "A paper airplane in flight",
        "A message in a bottle on the shore",
        "A Valentine heart with an arrow",
        "A Thanksgiving cornucopia",
        "A New Year Eve countdown clock",
        "A Chinese New Year dragon",
        "A Diwali lamp row",
        "A Day of the Dead sugar skull",
        "A harvest moon over a pumpkin patch",
        "A maypole with ribbons",
        "A Mardi Gras mask",
        "A trick-or-treater at a doorstep",
        "A menorah with glowing candles",
        "A Christmas tree with pixel ornaments",
        "A reindeer pulling a tiny sleigh",
        "A gingerbread man running away",
        "Mistletoe hanging from a doorway",
        "A cupid with a bow and arrow",
        "An egg hunt in a garden",
        "A leprechaun guarding gold",
        "A firecracker string going off",
        "A sparkler writing a word in the air",
        "A candy heart with a message",
        "A wreath on a front door",
        "A nutcracker soldier",
        "A snow angel from above",
        "An advent calendar with doors open",
        "Cherry blossoms for spring festival",
        "A summer solstice bonfire",
        "An autumn equinox harvest scene",
        "A winter solstice candle arrangement",
        "A spring garden coming alive",
        "Summer fruit arranged as a face",
        "Autumn leaves swirling in the wind",
        "First snowfall of winter on a town",
        "A scarecrow in a moonlit field",
        "A haunted house on a hill",
        "A witch flying across the moon",
        "A skeleton dancing",
        "A mummy escaping from bandages",
        "A black cat on a fence at night",
        "A New Year baby with a banner",
        "A sprite walk-cycle frame",
        "A tiny dungeon room with a door",
        "A floating island with waterfalls",
        "A health bar and UI elements",
        "A pixel-art self portrait",
        "A tile that could be a game floor",
        "An item shop with potions on shelves",
        "A boss monster with glowing eyes",
        "A treasure map with an X marks the spot",
        "A pixel-art sunset gradient",
        "A game over screen design",
        "A character select screen with icons",
        "A platformer level section",
        "A top-down RPG village",
        "A side-scrolling landscape",
        "A pixel-art loading screen tip",
        "A loot drop with sparkle effects",
        "A power-up item floating and spinning",
        "A pixel explosion effect",
        "A water ripple animation frame",
        "A campsite for saving the game",
        "A wanted poster on a wall",
        "A signpost at a crossroads",
        "A pixel-art dialogue box with portrait",
        "An inventory screen with items",
        "A minimap of a dungeon",
        "A title screen for a fictional game",
        "A key item glowing on a pedestal",
        "A locked door with a keyhole",
        "A breakable wall with cracks",
        "A spike trap in a dungeon floor",
        "A moving platform over lava",
        "A save point crystal",
        "A warp zone portal",
        "A hidden passage behind a waterfall",
        "A shop menu with buy and sell options",
        "A status screen with character stats",
        "An achievement badge design",
        "A pixel-art trophy on a shelf",
        "A victory fanfare scene with confetti",
        "A level complete screen",
        "A new quest notification scroll",
        "A crafting bench with materials",
        "A fishing minigame scene",
        "A cooking pot with ingredients around it",
        "A mount stable with different creatures",
        "A guild hall interior",
        "A pirate ship deck with cannons",
        "An enchantment table with runes",
        "A final boss arena entrance",
        "A pixel-art weather system",
        "A day-night cycle transition",
        "A farming plot with growing crops",
        "A pet companion following a hero",
        "A puzzle room with colored switches",
        "A minecart track through a mountain",
        "A treasure room after defeating a boss",
        "A character customization screen",
        "A world map with fog of war",
        "A pixel-art credits roll scene",
        "A respawn animation effect",
        "A dash trail effect behind a character",
        "A shield bash impact frame",
        "A magic spell charging up",
        "An arrow flying through the air",
        "A torch flickering on a dungeon wall",
        "A treasure goblin running away",
        "A mimic chest with teeth",
        "A slime enemy splitting in two",
        "A skeleton archer on a tower",
        "A fire elemental in a volcano",
        "An ice golem in a frozen cave",
        "A merchant caravan on a road",
        "A blacksmith upgrading a weapon",
        "A healing fountain in a town",
        "A mysterious NPC under a cloak",
        "A bounty board with wanted posters",
        "A chain lightning spell between enemies",
        "A summoning circle with a creature emerging",
        "A stealth attack from the shadows",
        "A victory pose after a boss fight",
        "A dragon egg about to hatch",
        "A pixel-art rain effect on a window",
        "A fishing bobber in a lake",
        "A procedural dungeon entrance",
        "A cutscene dialogue between two characters"
    ]

    // Returns today's prompt, deterministically chosen by the current date.
    static func todaysPrompt() -> String {
        let daysSinceEpoch = Calendar.current.ordinality(of: .day, in: .era, for: Date()) ?? 0
        let index = daysSinceEpoch % prompts.count
        return prompts[index]
    }

    // Returns the date string used for UserDefaults dismissal tracking.
    static func todaysKey() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return "dailyPromptDismissed_\(formatter.string(from: Date()))"
    }
}
